# Generated by Django 5.1.4 on 2024-12-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_capitulo_desc', models.IntegerField(blank=True, db_column='C_Capitulo_Desc', null=True)),
            ],
            options={
                'db_table': 'capitulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('l_link', models.CharField(blank=True, db_column='L_link', max_length=100, null=True)),
                ('l_book', models.CharField(blank=True, db_column='L_book', max_length=50, null=True)),
                ('l_libro_desc', models.CharField(blank=True, db_column='L_Libro_Desc', max_length=50, null=True)),
            ],
            options={
                'db_table': 'libros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Versiculos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'versiculos',
                'managed': False,
            },
        ),
    ]
